// <auto-generated />
using BankApplication.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BankApplication.API.Migrations
{
    [DbContext(typeof(BankApplicationContext))]
    [Migration("20180313063958_BankAppMigration")]
    partial class BankAppMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankApplication.API.Models.Account", b =>
                {
                    b.Property<int>("AccID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccNo");

                    b.Property<string>("AccType");

                    b.Property<int>("Bal");

                    b.HasKey("AccID");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankApplication.API.Models.AccRel", b =>
                {
                    b.Property<long>("AccNo")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccNoID");

                    b.HasKey("AccNo");

                    b.ToTable("AccRel");
                });

            modelBuilder.Entity("BankApplication.API.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Amount");

                    b.Property<long>("ReceiverAcc");

                    b.Property<long>("SenderAcc");

                    b.Property<DateTime>("XferTime");

                    b.HasKey("TransactionID");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankApplication.API.Models.User", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("AccNoListID");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<long>("PhoneNo");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
